Algoritmo "REPITA_MENU"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi

Var

   opcao: inteiro

Inicio

   repita
      escreval: ("1 - Dizer olá! ")
      escreval: ("2 - Dizer oi! ")
      escreval: ("0 - Sair do programa ")
      leia (opcao)
      se (opcao = 1) entao
         escreval ("Oi!")
      fimse
      se (opcao = 2) entao
         escreval ("Oi!")
      fimse
   ate (opcao = 0)
   Escreval ("Saiu do repita")


Fimalgoritmo