Algoritmo "ROBO_DO_WHATS"

Var
formaPagamento, opcao, novoPedido: inteiro
taxaEntrega, valorTotal: real
Inicio
escreval ("Boa noite, qual o seu pedido?")
repita

escreval ("1 - Deseja ver o cardapio?")
escreval ("2 - Já sei o meu pedido")
leia (opcao)
se (opcao = 1) entao
escreval ("nós temos 5 opções de deliciosos lanches:")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
Fimalgoritmo